//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Areas.AdminArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignStudentdToClass
    {
        public int AssignID { get; set; }
        public int RollNo { get; set; }
        public string SessionYear { get; set; }
        public int StudentID { get; set; }
        public int ClassSectionID { get; set; }
        public string PresentStatus { get; set; }
    
        public virtual Broker_ClassSection Broker_ClassSection { get; set; }
        public virtual Student Student { get; set; }
    }
}
