//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Areas.AdminArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker_TeacherSection
    {
        public int ID { get; set; }
        public int ClassSectionID { get; set; }
        public int TeacherID { get; set; }
        public bool IsClassTeacher { get; set; }
    
        public virtual Broker_ClassSection Broker_ClassSection { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
