//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Areas.AdminArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.Broker_SubjectTeacher = new HashSet<Broker_SubjectTeacher>();
            this.Broker_TeacherSection = new HashSet<Broker_TeacherSection>();
        }
    
        public int TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string Designation { get; set; }
        public string BirthDay { get; set; }
        public string Gender { get; set; }
        public string Image { get; set; }
        public string UserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Address { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Broker_SubjectTeacher> Broker_SubjectTeacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Broker_TeacherSection> Broker_TeacherSection { get; set; }
    }
}
