//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Areas.AdminArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedStudent
    {
        public int ArchivedStudentID { get; set; }
        public int RollNo { get; set; }
        public string SessionYear { get; set; }
        public string StudentRegID { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
    }
}
