//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Areas.AdminArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public int ClassSectionID { get; set; }
        public int StudentID { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public string UserID { get; set; }
        public string Comment { get; set; }
    
        public virtual Broker_ClassSection Broker_ClassSection { get; set; }
        public virtual Student Student { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
