//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Areas.AdminArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseCategory
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public bool IsActice { get; set; }
        public string CreatedBy { get; set; }
    }
}
