//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Areas.AdminArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPayment
    {
        public int PaymentID { get; set; }
        public string StudentRegID { get; set; }
        public int ClassSectionID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public decimal TotalAmmount { get; set; }
        public decimal PayAmmount { get; set; }
        public string Status { get; set; }
        public string PayMethod { get; set; }
        public string EntryBy { get; set; }
    
        public virtual Broker_ClassSection Broker_ClassSection { get; set; }
    }
}
