//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Management_System.Areas.AdminArea.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.AssignStudentdToClasses = new HashSet<AssignStudentdToClass>();
            this.Attendances = new HashSet<Attendance>();
        }
    
        public int StudentID { get; set; }
        public string StudentRegID { get; set; }
        public string StudentName { get; set; }
        public int ParentID { get; set; }
        public string BirthDate { get; set; }
        public string Gender { get; set; }
        public string Image { get; set; }
        public string UserID { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignStudentdToClass> AssignStudentdToClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
